// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6vqyYZ-EjMGKbfeJqWglR6RNcpG29liU',
    appId: '1:971950642735:web:a1809f257cb99da69d98da',
    messagingSenderId: '971950642735',
    projectId: 'shop-43928',
    authDomain: 'shop-43928.firebaseapp.com',
    storageBucket: 'shop-43928.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzwVEF8zZh1qDfQrR-8DknhxAXSHXBdXg',
    appId: '1:971950642735:android:ebe2a79f7c540e449d98da',
    messagingSenderId: '971950642735',
    projectId: 'shop-43928',
    storageBucket: 'shop-43928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn1KWZ2o32QmRi93vNi24Ejzb3Pv75Yro',
    appId: '1:971950642735:ios:96518de9887860699d98da',
    messagingSenderId: '971950642735',
    projectId: 'shop-43928',
    storageBucket: 'shop-43928.appspot.com',
    androidClientId: '971950642735-bcbh4t5i5ih71lldbn1ukecvla5nm28l.apps.googleusercontent.com',
    iosClientId: '971950642735-t7meha757313pe34hvqlq4pcvsm34po8.apps.googleusercontent.com',
    iosBundleId: 'az.masterstudio.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn1KWZ2o32QmRi93vNi24Ejzb3Pv75Yro',
    appId: '1:971950642735:ios:96518de9887860699d98da',
    messagingSenderId: '971950642735',
    projectId: 'shop-43928',
    storageBucket: 'shop-43928.appspot.com',
    androidClientId: '971950642735-bcbh4t5i5ih71lldbn1ukecvla5nm28l.apps.googleusercontent.com',
    iosClientId: '971950642735-t7meha757313pe34hvqlq4pcvsm34po8.apps.googleusercontent.com',
    iosBundleId: 'az.masterstudio.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6vqyYZ-EjMGKbfeJqWglR6RNcpG29liU',
    appId: '1:971950642735:web:5403aab6a0ef76ea9d98da',
    messagingSenderId: '971950642735',
    projectId: 'shop-43928',
    authDomain: 'shop-43928.firebaseapp.com',
    storageBucket: 'shop-43928.appspot.com',
  );

}